/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueadero.presentacion;

import mvcf.AModel;
import mvcf.AView;
import parqueadero.clientemain.RunMVC;
import parqueadero.negocio.GestorVigilante;
import parqueadero.negocio.UsuarioPost;
import parqueadero.utils.Utilidades;

/**
 *
 * @author Breiner Mamian
 */
public class GUILogin extends javax.swing.JFrame implements AView {
    
    private Object bean;

    /**
     * Creates new customizer GUIVigilante
     */
    public GUILogin() {
        initComponents();
        this.setSize(250, 390);
        this.setLocation(70, 70);
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFCodigoVig = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Clavetxt = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Código");
        jPanel3.add(jLabel2);
        jPanel3.add(jTFCodigoVig);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clave Acceso");
        jPanel3.add(jLabel1);
        jPanel3.add(Clavetxt);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recibo-entrada.png"))); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descargaicon.png"))); // NOI18N
        jPanel4.add(jLabel3);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling co
        GestorVigilante gestor = new GestorVigilante();
        String id = jTFCodigoVig.getText().trim();
        
        if (id.equals("")) {
            return;
        }
        // Busca el cliente en la base de datos Central
        UsuarioPost usu = gestor.buscarVigilanteCentral(id);
        
        if (usu==null) {
            //Si no se encontro el ID del Vigilante.
            Utilidades.mensajeError("Identificación NO valida.", "Atención");
        }else{
            //Validamos ClaveAcceso.
            if(Clavetxt.getText().trim().equals(usu.getPass_usu())){
                Utilidades.mensajeExito("Bienvenido.", "Verificado");
                this.setVisible(false);
                RunMVC mainRunMVC = new RunMVC();
            }else{
                Utilidades.mensajeError("Codigo Invalido.", "Atención");

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Clavetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTFCodigoVig;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel amodel) {
    }
}
