package parqueadero.presentacion;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;
import parqueadero.negocio.Cliente;
import parqueadero.negocio.ClienteVehiculo;
import parqueadero.negocio.ClienteVehiculoPost;
import parqueadero.negocio.GestorClienteVehiculo;
import parqueadero.negocio.GestorClientes;
import parqueadero.negocio.GestorVehiculo;
import parqueadero.negocio.Vehiculo;
import parqueadero.negocio.VehiculoPost;
import parqueadero.utils.Utilidades;

/**
 *
 * @author Adrian
 */
public class GUIPrincipal extends javax.swing.JFrame implements AView {

    private String accion;

    public GUIPrincipal() {
        initComponents();

        super.setSize(770, 650);
        super.setLocation(50, 70);
        inicializarTabla();
        inicializarTabla2();
        //fijarMensajeExplicacion();

        this.botonesEstadoInicial();
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);

        buttonGroup2.add(Femenino);
        buttonGroup2.add(Masculino);
    }

    public JButton getBtnRetirar() {
        return btnRetirar;
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngresoRetirar = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlCrearUsuId = new javax.swing.JPanel();
        lblCrearUsuId = new javax.swing.JLabel();
        txtCrearUsuId = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCrearCliNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCrearCliApe = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        Masculino = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        roling = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        FechaCli = new com.toedter.calendar.JCalendar();
        jPanel21 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Marcatxt = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Placatxt = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TipoCBox = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtColorVehi = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtIdClienteAsoc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPlacaAsoc = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        btnAsociacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel32 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        lbl_placa_mul = new javax.swing.JLabel();
        txt_placa_mul = new javax.swing.JTextField();
        lbl_des_multa = new javax.swing.JLabel();
        txt_des_mul = new javax.swing.JTextField();
        lbl_url_multa = new javax.swing.JLabel();
        txt_url_multa = new javax.swing.JTextField();
        lbl_fecha_mul = new javax.swing.JLabel();
        calendar_multa = new com.toedter.calendar.JCalendar();
        jPanel36 = new javax.swing.JPanel();
        btn_multa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setLayout(new java.awt.GridLayout(3, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setText("PARQUEADERO UNIVERSIDAD DEL CAUCA");
        jPanel3.add(jLabel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jRadioButton1.setText("Busqueda por Cedula");
        jRadioButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButton1);

        jRadioButton2.setText("Busqueda por código");
        jRadioButton2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jRadioButton2);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setText("Numero de identificación:");
        jPanel6.add(jLabel2);
        jPanel6.add(txtId);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel6.add(btnBuscar);

        jPanel3.add(jPanel6);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recibo-entrada.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        jPanel7.add(btnIngresar);

        btnRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/recibo-salida.png"))); // NOI18N
        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel7.add(btnRetirar);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar.png"))); // NOI18N
        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        tblIngresoRetirar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIngresoRetirar);

        jPanel8.add(jScrollPane1);

        jPanel4.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jTabbedPane1.addTab("Gestión Parqueadero", jPanel2);

        jPanel9.setLayout(new java.awt.GridLayout(4, 0));

        jPanel19.setLayout(new java.awt.GridLayout(2, 0));

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gestion Usuarios");
        jPanel10.add(jLabel3);

        jPanel19.add(jPanel10);

        pnlCrearUsuId.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblCrearUsuId.setText("Identificación:");
        pnlCrearUsuId.add(lblCrearUsuId);

        txtCrearUsuId.setPreferredSize(new java.awt.Dimension(250, 50));
        pnlCrearUsuId.add(txtCrearUsuId);

        jPanel19.add(pnlCrearUsuId);

        jPanel9.add(jPanel19);

        jPanel20.setLayout(new java.awt.GridLayout(2, 0));

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 18, 5));

        jLabel5.setText("Nombre :");
        jPanel14.add(jLabel5);

        txtCrearCliNombre.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel14.add(txtCrearCliNombre);

        jLabel4.setText("Apellido:");
        jPanel14.add(jLabel4);

        txtCrearCliApe.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel14.add(txtCrearCliApe);

        jPanel20.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        jLabel6.setText("Sexo:");
        jPanel15.add(jLabel6);

        Femenino.setText("Femenino");
        jPanel15.add(Femenino);

        Masculino.setText("Masculino");
        jPanel15.add(Masculino);

        jPanel20.add(jPanel15);

        jPanel9.add(jPanel20);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 18, 5));

        jLabel7.setText("Rol:");
        jPanel17.add(jLabel7);

        roling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estudiante", "docente", "administrativo" }));
        roling.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel17.add(roling);

        jPanel16.add(jPanel17);

        jLabel8.setText("Fecha de nacimiento:");
        jPanel16.add(jLabel8);
        jPanel16.add(FechaCli);

        jPanel9.add(jPanel16);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/grabar.png"))); // NOI18N
        jButton3.setText("Registrar");
        jButton3.setMinimumSize(new java.awt.Dimension(20, 7));
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton3);

        jPanel21.add(jPanel18);

        jPanel9.add(jPanel21);

        jTabbedPane1.addTab("Gestión Usuarios", jPanel9);

        jPanel22.setLayout(new java.awt.GridLayout(6, 0, 0, 15));

        jPanel23.setLayout(new java.awt.GridLayout(1, 0));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gestión Vehiculos");
        jPanel23.add(jLabel9);

        jPanel22.add(jPanel23);

        jPanel25.setLayout(new java.awt.GridLayout(1, 0));

        jLabel11.setText("Marca:");
        jPanel25.add(jLabel11);
        jPanel25.add(Marcatxt);

        jPanel22.add(jPanel25);

        jPanel24.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setText("Placa:");
        jPanel24.add(jLabel10);
        jPanel24.add(Placatxt);

        jPanel22.add(jPanel24);

        jPanel26.setLayout(new java.awt.GridLayout(1, 0));

        jLabel12.setText("Tipo:");
        jPanel26.add(jLabel12);

        TipoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moto", "Auto" }));
        jPanel26.add(TipoCBox);

        jPanel22.add(jPanel26);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        jLabel16.setText("Color:");
        jPanel13.add(jLabel16);
        jPanel13.add(txtColorVehi);

        jPanel22.add(jPanel13);

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/grabar.png"))); // NOI18N
        jButton5.setText("Registrar");
        jButton5.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton5);

        jPanel22.add(jPanel27);

        jTabbedPane1.addTab("Gestión Vehiculos", jPanel22);

        jPanel28.setLayout(new java.awt.GridLayout(1, 0));

        jPanel29.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Gestión Asociación");
        jPanel31.add(jLabel15);

        jPanel29.add(jPanel31, java.awt.BorderLayout.NORTH);

        jPanel30.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Número de identificación:");
        jPanel30.add(jLabel14, new java.awt.GridBagConstraints());

        txtIdClienteAsoc.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel30.add(txtIdClienteAsoc, new java.awt.GridBagConstraints());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Placa de Vehiculo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel30.add(jLabel13, gridBagConstraints);

        txtPlacaAsoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlacaAsoc.setPreferredSize(new java.awt.Dimension(200, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel30.add(txtPlacaAsoc, gridBagConstraints);

        jPanel29.add(jPanel30, java.awt.BorderLayout.CENTER);

        btnAsociacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N
        btnAsociacion.setText("Realizar Asociación");
        btnAsociacion.setMinimumSize(new java.awt.Dimension(20, 7));
        btnAsociacion.setPreferredSize(new java.awt.Dimension(250, 50));
        btnAsociacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociacionActionPerformed(evt);
            }
        });
        jPanel33.add(btnAsociacion);

        jPanel29.add(jPanel33, java.awt.BorderLayout.SOUTH);

        jPanel28.add(jPanel29);

        jTabbedPane1.addTab("Gestión Asociación", jPanel28);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2);

        jPanel1.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblClientes);

        jPanel12.add(jScrollPane3);

        jPanel1.add(jPanel12, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Base de Datos Local", jPanel1);

        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Gestión de Multas");
        jLabel17.setToolTipText("");
        jPanel34.add(jLabel17);

        jPanel32.add(jPanel34, java.awt.BorderLayout.NORTH);

        jPanel35.setLayout(new java.awt.GridLayout(4, 2, 0, 5));

        lbl_placa_mul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_placa_mul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_placa_mul.setText("Placa:");
        jPanel35.add(lbl_placa_mul);

        txt_placa_mul.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel35.add(txt_placa_mul);

        lbl_des_multa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_des_multa.setText("Descripción:");
        jPanel35.add(lbl_des_multa);

        txt_des_mul.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel35.add(txt_des_mul);

        lbl_url_multa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_url_multa.setText("URL Foto:");
        jPanel35.add(lbl_url_multa);

        txt_url_multa.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel35.add(txt_url_multa);

        lbl_fecha_mul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_fecha_mul.setText("Fecha:");
        jPanel35.add(lbl_fecha_mul);
        jPanel35.add(calendar_multa);

        jPanel32.add(jPanel35, java.awt.BorderLayout.CENTER);

        btn_multa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_multa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        btn_multa.setText("Multar");
        jPanel36.add(btn_multa);

        jPanel32.add(jPanel36, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Gestión de Multas", jPanel32);

        getContentPane().add(jTabbedPane1);

        jMenu1.setText("Configuracion");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informacion");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.inicializarTabla();
        String id = txtId.getText().trim();
        GestorClienteVehiculo gestor2 = new GestorClienteVehiculo();
        GestorClientes gestor = new GestorClientes();

        //VALIDACION DE QUE EL CAMPO DEL ID NO SEA VACIO 
        if (id.equals("")) {
            return;
        }
        Cliente cli = null;
        List<ClienteVehiculo> clivelocal = null;
        ClienteVehiculoPost[] clive;

        // SE HACE LA BUSQUEDA INICIALMENTE EN LA BD LOCAL
        try {
            clivelocal = gestor.consultarVehiCliente(id);

            //SI EL CLIENTE BUSCADO EN LA BD LOCAL ES NULL SE PROCEDE A BUSCARLO EN LA BD CENTRAL
            if (clivelocal.isEmpty()) {

                if (jRadioButton1.isSelected()) {
                    //BUSQUEDA POR IDCLIENTE
                    cli = gestor.buscarClienteCentral(id);

                    //SI EL CLIENTE SE ENCUENTRA EN LA BASE DE DATOS SE PROCEDE A VERIFICAR SI HAY UN CLIENTEVEHICULO
                    clive = gestor2.buscarClienteVehiculoEnCentral(id);
                } else if (jRadioButton2.isSelected()) {
                    //BUSQUEDA POR CODIGOCLIENTE FALTA POR HACER
                    cli = gestor.buscarClienteCentral(id);
                    //SI EL CLIENTE SE ENCUENTRA EN LA BASE DE DATOS SE PROCEDE A VERIFICAR SI HAY UN CLIENTEVEHICULO
                    clive = gestor2.buscarClienteVehiculoEnCentral(id);
                } else {
                    Utilidades.mensajeError("No ha seleccionado el tipo de documento", "Buscar Cliente");
                    return;
                }

                //VERIFICACION DE QUE SI EXITE EL CLIENTEVEHICULO
                if (clive != null) {
                    //ENCONTRADO EN LA CENTRAL

                    ClienteVehiculoPost[] lista = gestor2.buscarClientesVehiculosEnCentral(id);
                    fijarCamposTabla2(lista);
                    btnIngresar.setEnabled(true);
                    btnRetirar.setEnabled(true);
                } else {
                    if (cli != null) {
                        Utilidades.mensajeError("El cliente NO tiene vehiculo asociado", "Error");
                    } else {
                        Utilidades.mensajeError("El cliente NO existe", "Error");
                    }
                }

            } else {
                //SI ENTRA EN ESTE CONDICIONAL ES POR QUE EL CLIENTE EN LA BD LOCAL NO ES NULL
                //ENCONTRADO EN LA LOCAL
                fijarCamposTabla(clivelocal);
                btnIngresar.setEnabled(true);
                btnRetirar.setEnabled(true);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al buscar el cliente en la base de datos local del parqueadero", "Atención");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Registrar Un cliente en la base de datos Central
        String idcliente = txtCrearUsuId.getText().trim();
        String nomclienteing = txtCrearCliNombre.getText().trim();
        String apeclienteing = txtCrearCliApe.getText().trim();
        String sexoclienteing = "";
        if (Femenino.isSelected()) {
            sexoclienteing = "FEMENINO";
        }
        else if (Masculino.isSelected()) {
            sexoclienteing = "MASCULINO";
        }
        else{
            Utilidades.mensajeAdvertencia("No ha seleccionado el genero", "Crear Cliente");
        }
        String clifechanacimiento = FechaCli.getCalendar().get(Calendar.DAY_OF_MONTH) + "-";
        clifechanacimiento = clifechanacimiento + FechaCli.getCalendar().get(Calendar.MARCH) + "-";
        clifechanacimiento = clifechanacimiento + FechaCli.getCalendar().get(Calendar.YEAR) + "";

        String rolCli = ((String) roling.getSelectedItem()).toUpperCase();
        String info = String.format("%s,%s,%s,%s,%s,%s", idcliente,nomclienteing ,apeclienteing,sexoclienteing,clifechanacimiento,rolCli);

        GestorClientes gestor = new GestorClientes();
        gestor.IngresarClienteCentral(info);
        Utilidades.mensajeExito("Se registro un nuevo cliente en la central", "Gestión Usuarios");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO INGRESAR VEHICULO EN CENTRAL
        GestorVehiculo gestor = new GestorVehiculo();
        String info;

        info = String.format("%s,%s,%s,%s",Placatxt.getText().toUpperCase().trim(),
                Marcatxt.getText().toUpperCase().trim(),
                TipoCBox.getSelectedItem().toString().toUpperCase(), 
                txtColorVehi.getText().toUpperCase().trim());

        String respuesta = gestor.IngresarVehiculoCentral(info);
        if(respuesta.equals("OK")) {
            Utilidades.mensajeExito("Se registro un nuevo vehiculo en la central", "Gestión Vehiculos");
        } else {
            Utilidades.mensajeError(String.format("NO se registro el vehiculo en la central\n%s", respuesta), "Gestión Vehiculos");
        }
        

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnAsociacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociacionActionPerformed
        // Gestion De Asociaciones
        String id = txtIdClienteAsoc.getText().trim();
        String placa = txtPlacaAsoc.getText().toUpperCase().trim();

        //validacion De datos
        GestorClientes gestcli = new GestorClientes();
        Cliente aux1 = gestcli.buscarClienteCentral(id);
        GestorVehiculo gestVehi = new GestorVehiculo();
        VehiculoPost aux2 = gestVehi.buscarVehiculoCentral(placa);
        
        if (aux1 != null && aux2 != null) {
                Utilidades.mensajeExito("Datos Validos", "Asociación");
                String info = String.format("%s,%s",id, placa);
                GestorClienteVehiculo gestclive = new GestorClienteVehiculo();
                String respuessta = gestclive.IngresarClienteVehiculoCentral(info);
                if(respuessta.equals("OK"))
                    Utilidades.mensajeExito("Se realizó la asociación", "Asociación");
                else
                    Utilidades.mensajeError(String.format("Ocurrio un erro en la central: %s", respuessta), "Asociación");
        } else {
            Utilidades.mensajeError("Datos NO validos", "Asociación");
        }

    }//GEN-LAST:event_btnAsociacionActionPerformed

    public boolean validarFormulario() {
        if (this.getId().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar la identificación del empleado", "Atención");
            txtId.requestFocus();
            return false;
        }
        if (this.getNombres().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar los nombres del empleado", "Atención");
            //jTable1.getValueAt(0, 1).requestFocus();
            return false;
        }

        if (this.getApellidos().equals("")) {
            Utilidades.mensajeAdvertencia("Debe agregar los apellidos del empleado", "Atención");
            //jTextField2.requestFocus();
            return false;
        }
        return true;
    }

    public String getId() {
        String aux = "" + tblIngresoRetirar.getValueAt(0, 0);
        return Utilidades.capitalize(aux.trim());
    }

    public String getNombres() {
        String aux = "" + tblIngresoRetirar.getValueAt(0, 1);
        return Utilidades.capitalize(aux.trim());

        //return Utilidades.capitalize(jTextField1.getText().trim());
    }

    public String getApellidos() {

        String aux = "" + tblIngresoRetirar.getValueAt(0, 2);
        return Utilidades.capitalize(aux.trim());
    }

    public String getDireccion() {

        String aux = "" + tblIngresoRetirar.getValueAt(0, 3);
        return Utilidades.capitalize(aux.trim());
    }

    public String getCelular() {

        int iplaca = tblIngresoRetirar.getSelectedRow();

        String aux = "" + tblIngresoRetirar.getValueAt(iplaca, 4);
        return Utilidades.capitalize(aux.trim());
    }

    public String getEmail() {

        String aux = "" + tblIngresoRetirar.getValueAt(0, 5);
        return Utilidades.capitalize(aux.trim());
    }

    public JTable getTblIngresoRetirar() {
        return tblIngresoRetirar;
    }

    public void botonesEstadoInicial() {
        btnIngresar.setEnabled(false);
        btnRetirar.setEnabled(false);
    }

    private void fijarCamposTabla(Cliente cli) {

        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblIngresoRetirar.getModel();

        Object rowData[] = new Object[7];

        rowData[0] = cli.getIdCliente();
        rowData[1] = cli.getNombre();
        rowData[2] = cli.getApellido();
        rowData[3] = cli.getGenero();
        rowData[4] = cli.getFechaNacimiento();
        rowData[5] = cli.getRol();

        model.addRow(rowData);

    }

    private void fijarCamposTabla2(ClienteVehiculoPost[] list) {

        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblIngresoRetirar.getModel();

        Object rowData[] = new Object[7];
        for (int i = 0; i < list.length; i++) {
            rowData[0] = list[i].getId_cli();
            rowData[1] = list[i].getNombre_cli();
            rowData[2] = list[i].getApellido_cli();
            rowData[3] = list[i].getRol_cli();
            rowData[4] = list[i].getPlaca_vehi();
            rowData[5] = list[i].getTipo_vehi();
            model.addRow(rowData);
        }
    }

    private void fijarCamposTabla(List<ClienteVehiculo> list) {

        this.inicializarTabla2();
        DefaultTableModel model = (DefaultTableModel) tblIngresoRetirar.getModel();

        Object rowData[] = new Object[7];

        for (ClienteVehiculo clive : list) {
            rowData[0] = clive.getIdCliente();
            rowData[1] = clive.getNombre();
            rowData[2] = clive.getApellido();
            //rowData[3] = clive.getIdvehiculo();
            rowData[3] = clive.getNodeplaca();
            rowData[4] = clive.getTipoVehiculo();
            model.addRow(rowData);
        }
    }

    private void inicializarTabla() {

        tblIngresoRetirar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id Cliente", "Nombre Cliente", "Apellido Cliente", "Rol Cliente", "Placa Vehiculo", "Tipo Vehiculo"}
        ));
    }

    private void inicializarTabla2() {

        tblIngresoRetirar.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Id", "Nombres", "Apellidos", "Placa", "Tipo"}
        ));
    }

    public void limpiarCajas(boolean todas) {
        if (todas) {
            txtId.setText("");
        }
//        lblMensaje.setText("");
//        txtNombres.setText("");
//        txtApellidos.setText("");
//        txtDireccion.setText("");
//        txtCelular.setText("");
//        txtEmail.setText("");

    }

    private void fijarCamposTabla(ClienteVehiculo clive) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblIngresoRetirar.getModel();

        Object rowData[] = new Object[7];

        rowData[0] = clive.getIdCliente();
        rowData[1] = clive.getNombre();
        rowData[2] = clive.getApellido();
        rowData[3] = clive.getIdvehiculo();
        rowData[4] = clive.getNodeplaca();
        rowData[5] = clive.getTipoVehiculo();

        model.addRow(rowData);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar FechaCli;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JTextField Marcatxt;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JTextField Placatxt;
    private javax.swing.JComboBox<String> TipoCBox;
    private javax.swing.JButton btnAsociacion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btn_multa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JCalendar calendar_multa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCrearUsuId;
    private javax.swing.JLabel lbl_des_multa;
    private javax.swing.JLabel lbl_fecha_mul;
    private javax.swing.JLabel lbl_placa_mul;
    private javax.swing.JLabel lbl_url_multa;
    private javax.swing.JPanel pnlCrearUsuId;
    private javax.swing.JComboBox<String> roling;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblIngresoRetirar;
    private javax.swing.JTextField txtColorVehi;
    private javax.swing.JTextField txtCrearCliApe;
    private javax.swing.JTextField txtCrearCliNombre;
    private javax.swing.JTextField txtCrearUsuId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdClienteAsoc;
    private javax.swing.JTextField txtPlacaAsoc;
    private javax.swing.JTextField txt_des_mul;
    private javax.swing.JTextField txt_placa_mul;
    private javax.swing.JTextField txt_url_multa;
    // End of variables declaration//GEN-END:variables

    private void llenarTabla(ArrayList<Cliente> clientes) {
        this.inicializarTabla();
        DefaultTableModel model = (DefaultTableModel) tblClientes.getModel();

        Object rowData[] = new Object[7];
        for (Cliente cli : clientes) {
            rowData[0] = cli.getIdCliente();
            rowData[1] = cli.getNombre();
            rowData[2] = cli.getApellido();
            rowData[3] = cli.getGenero();
            rowData[4] = cli.getFechaNacimiento();
            rowData[5] = cli.getRol();

            model.addRow(rowData);
        }
    }

    @Override
    public void actualizar(AModel amodel) {
        try {
            GestorClientes gestor = (GestorClientes) amodel;
            ArrayList<Cliente> listado = gestor.consultarClientes();
            llenarTabla(listado);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            Utilidades.mensajeError("Error al consultar clientes", "Atención");
        }
    }

    public JButton getBtnMultar() {
        return btn_multa;
    }

    public String getTxt_des_mul() {
        return txt_des_mul.getText();
    }

    public String getTxt_placa_mul() {
        return txt_placa_mul.getText();
    }

    public String getTxt_url_multa() {
        return txt_url_multa.getText();
    }
    
    public String getAccion() {
        return accion;
    }

    public void setAccion(String accion) {
        this.accion = accion;
    }
}
